[workspace]
members = [".", "benchmarks/micro"]

[package]
name = "iobeam"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
arrayvec = "0.7.6"
clap = "4.6.1"
httparse = "1.10.1"
io-uring = "0.7.12"
itoa = "1.0.18"
libc = { version = "0.2.185", default-features = false }
mime_guess = "2.0.5"
percent-encoding = "2.3.2"
slab = "0.4.12"
